server:
  port: 11702

spring:
  application:
    name: hotwater-service
  h2:
    console:
      enabled: true

eureka:
  instance:
    instanceId: "${spring.application.name}:${random.value}"
    preferIpAddress: true
