server:
  port: 11701

spring:
  application:
    name: device-service
  h2:
    console:
      enabled: true

logging:
  level:
    ROOT: INFO

eureka:
  instance:
    instanceId: "${spring.application.name}:${random.value}"
    preferIpAddress: true
