server:
  port: 11700

spring:
  application:
    name: logging-service
  h2:
    console:
      enabled: true

eureka:
  instance:
    instanceId: "${spring.application.name}:${random.value}"
    preferIpAddress: true
